config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title
  validates_length_of :title, minimum: 5, allow_blank: false


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new

  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    # @article = Article.new(params.require(:article).permit(:title, :text))
    @article = Article.new(article_params)
    # render plain: params[:article].inspect
    if @article.save
      redirect_to(@article)
    else
      render "articles/new"
    end
    end

  def update
    @article = Article.find(params[:id])

    if@article.update(article_params)
      redirect_to@article
    else
      render "articles/edit"
    end
  end

  def show
    @article = Article.find(params[:id])
  end



  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= form_for (@article) do | f | %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br/>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to('Back', articles_path) %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to'New article',new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Options</th>

  </tr>

  <%= @articles.each do | article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to('Show', article_path(article)) %>/<%= link_to('Edit', article_path(article)) %></td>
  </tr>
<% end %>
</table>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do | f | %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br/>
   <%= f.text_field :title %>
 </p>
<p>
  <%= f.label :text %><br/>
  <%= f.text_area :text %>
</p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to('Back', articles_path) %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
  <p>
    <strong>Text:</strong>

    <%= @article.text %>

  </p>
<%= link_to('Back', articles_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails 6!</h1>
<%= link_to 'My Blog',welcome_index_url %>